"""update site wishlist table

Revision ID: 0080960af144
Revises: bd611b5b4853
Create Date: 2025-09-28 17:43:30.274987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0080960af144'
down_revision = 'bd611b5b4853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_wishlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wishlist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_site_wishlists_site_id_sites'), 'sites', ['site_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_site_wishlists_wishlist_id_user_wishlists'), 'user_wishlists', ['wishlist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_wishlists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_site_wishlists_wishlist_id_user_wishlists'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_site_wishlists_site_id_sites'), type_='foreignkey')
        batch_op.drop_column('wishlist_id')
        batch_op.drop_column('site_id')

    # ### end Alembic commands ###
