"""create cities table

Revision ID: 8397719aa22c
Revises: d92e7c634fcb
Create Date: 2025-09-28 10:36:53.939592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8397719aa22c'
down_revision = 'd92e7c634fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('city_img', sa.String(), nullable=False),
    sa.Column('city_intro', sa.String(), nullable=False),
    sa.Column('population', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_cities_country_id_countries')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sites_city_id_cities'), 'cities', ['city_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sites_city_id_cities'), type_='foreignkey')
        batch_op.drop_column('city_id')

    op.drop_table('cities')
    # ### end Alembic commands ###
