"""create user wishlist table

Revision ID: bd611b5b4853
Revises: 97bae63eaecf
Create Date: 2025-09-28 17:38:16.978545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd611b5b4853'
down_revision = '97bae63eaecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_wishlists_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_wishlists')
    op.drop_table('site_wishlists')
    # ### end Alembic commands ###
