"""create site interest table

Revision ID: d92e7c634fcb
Revises: 3896667e6a75
Create Date: 2025-09-27 20:44:10.782674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92e7c634fcb'
down_revision = '3896667e6a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(), nullable=False),
    sa.Column('interest_img', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interest')
    )
    op.create_table('site_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name=op.f('fk_site_interests_interest_id_interests')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_site_interests_site_id_sites')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_interests')
    op.drop_table('interests')
    # ### end Alembic commands ###
